"""Hardcoded selection of 5 public-domain stories for ArcVault Seed.

Every excerpt below is the verbatim opening of the real story (~500 words),
pulled from Project Gutenberg's plain-text editions — not paraphrased. Sources
are cited per entry so a reader can verify against the original.
"""

STORIES = {
    "oval-portrait": {
        "title": "The Oval Portrait",
        "author": "Edgar Allan Poe",
        "source": "The Works of Edgar Allan Poe, Vol. 1 (Project Gutenberg #2147)",
        "text": "The château into which my valet had ventured to make forcible "
                "entrance, rather than permit me, in my desperately wounded condition, "
                "to pass a night in the open air, was one of those piles of commingled "
                "gloom and grandeur which have so long frowned among the Appennines, "
                "not less in fact than in the fancy of Mrs. Radcliffe. To all "
                "appearance it had been temporarily and very lately abandoned. We "
                "established ourselves in one of the smallest and least sumptuously "
                "furnished apartments. It lay in a remote turret of the building. Its "
                "decorations were rich, yet tattered and antique. Its walls were hung "
                "with tapestry and bedecked with manifold and multiform armorial "
                "trophies, together with an unusually great number of very spirited "
                "modern paintings in frames of rich golden arabesque. In these "
                "paintings, which depended from the walls not only in their main "
                "surfaces, but in very many nooks which the bizarre architecture of the "
                "château rendered necessary—in these paintings my incipient delirium, "
                "perhaps, had caused me to take deep interest; so that I bade Pedro to "
                "close the heavy shutters of the room—since it was already night—to "
                "light the tongues of a tall candelabrum which stood by the head of my "
                "bed, and to throw open far and wide the fringed curtains of black "
                "velvet which enveloped the bed itself. I wished all this done that I "
                "might resign myself, if not to sleep, at least alternately to the "
                "contemplation of these pictures, and the perusal of a small volume "
                "which had been found upon the pillow, and which purported to criticise "
                "and describe them. Long, long I read—and devoutly, devotedly I gazed. "
                "Rapidly and gloriously the hours flew by and the deep midnight came. "
                "The position of the candelabrum displeased me, and outreaching my hand "
                "with difficulty, rather than disturb my slumbering valet, I placed it "
                "so as to throw its rays more fully upon the book. But the action "
                "produced an effect altogether unanticipated. The rays of the numerous "
                "candles (for there were many) now fell within a niche of the room "
                "which had hitherto been thrown into deep shade by one of the "
                "bed-posts. I thus saw in vivid light a picture all unnoticed before. "
                "It was the portrait of a young girl just ripening into womanhood. I "
                "glanced at the painting hurriedly, and then closed my eyes. Why I did "
                "this was not at first apparent even to my own perception. But while my "
                "lids remained thus shut, I ran over in my mind my reason for so "
                "shutting them. It was an impulsive movement to gain time for "
                "thought—to make sure that my vision had not deceived me—to calm and "
                "subdue my fancy for a more sober and more certain gaze. In a very few "
                "moments I again looked fixedly at the painting. That I now saw aright "
                "I could not and would not doubt; for the first flashing of the candles "
                "upon that canvas had seemed to dissipate the dreamy stupor which was "
                "stealing over my senses, and to startle me at once into waking life.",
    },
    "gift-of-the-magi": {
        "title": "The Gift of the Magi",
        "author": "O. Henry",
        "source": "The Gift of the Magi (Project Gutenberg #7256)",
        "text": "One dollar and eighty-seven cents. That was all. And sixty cents of "
                "it was in pennies. Pennies saved one and two at a time by "
                "bulldozing the grocer and the vegetable man and the butcher until "
                "one’s cheeks burned with the silent imputation of parsimony that "
                "such close dealing implied. Three times Della counted it. One "
                "dollar and eighty-seven cents. And the next day would be Christmas. "
                "There was clearly nothing to do but flop down on the shabby little "
                "couch and howl. So Della did it. Which instigates the moral "
                "reflection that life is made up of sobs, sniffles, and smiles, with "
                "sniffles predominating. While the mistress of the home is gradually "
                "subsiding from the first stage to the second, take a look at the "
                "home. A furnished flat at $8 per week. It did not exactly beggar "
                "description, but it certainly had that word on the lookout for the "
                "mendicancy squad. In the vestibule below was a letter-box into "
                "which no letter would go, and an electric button from which no "
                "mortal finger could coax a ring. Also appertaining thereunto was a "
                "card bearing the name “Mr. James Dillingham Young.” The "
                "“Dillingham” had been flung to the breeze during a former period of "
                "prosperity when its possessor was being paid $30 per week. Now, "
                "when the income was shrunk to $20, though, they were thinking "
                "seriously of contracting to a modest and unassuming D. But whenever "
                "Mr. James Dillingham Young came home and reached his flat above he "
                "was called “Jim” and greatly hugged by Mrs. James Dillingham Young, "
                "already introduced to you as Della. Which is all very good. Della "
                "finished her cry and attended to her cheeks with the powder rag. "
                "She stood by the window and looked out dully at a gray cat walking "
                "a gray fence in a gray backyard. Tomorrow would be Christmas Day, "
                "and she had only $1.87 with which to buy Jim a present. She had "
                "been saving every penny she could for months, with this result. "
                "Twenty dollars a week doesn’t go far. Expenses had been greater "
                "than she had calculated. They always are. Only $1.87 to buy a "
                "present for Jim. Her Jim. Many a happy hour she had spent planning "
                "for something nice for him. Something fine and rare and "
                "sterling—something just a little bit near to being worthy of the "
                "honor of being owned by Jim. There was a pier glass between the "
                "windows of the room. Perhaps you have seen a pier glass in an $8 "
                "flat. A very thin and very agile person may, by observing his "
                "reflection in a rapid sequence of longitudinal strips, obtain a "
                "fairly accurate conception of his looks. Della, being slender, had "
                "mastered the art. Suddenly she whirled from the window and stood "
                "before the glass. Her eyes were shining brilliantly, but her face "
                "had lost its color within twenty seconds. Rapidly she pulled down "
                "her hair and let it fall to its full length.",
    },
    "speckled-band": {
        "title": "The Adventure of the Speckled Band",
        "author": "Arthur Conan Doyle",
        "source": "The Adventures of Sherlock Holmes (Project Gutenberg #1661)",
        "text": "On glancing over my notes of the seventy odd cases in which I have "
                "during the last eight years studied the methods of my friend Sherlock "
                "Holmes, I find many tragic, some comic, a large number merely strange, "
                "but none commonplace; for, working as he did rather for the love of "
                "his art than for the acquirement of wealth, he refused to associate "
                "himself with any investigation which did not tend towards the unusual, "
                "and even the fantastic. Of all these varied cases, however, I cannot "
                "recall any which presented more singular features than that which was "
                "associated with the well-known Surrey family of the Roylotts of Stoke "
                "Moran. The events in question occurred in the early days of my "
                "association with Holmes, when we were sharing rooms as bachelors in "
                "Baker Street. It is possible that I might have placed them upon record "
                "before, but a promise of secrecy was made at the time, from which I "
                "have only been freed during the last month by the untimely death of "
                "the lady to whom the pledge was given. It is perhaps as well that the "
                "facts should now come to light, for I have reasons to know that there "
                "are widespread rumours as to the death of Dr. Grimesby Roylott which "
                "tend to make the matter even more terrible than the truth. It was "
                "early in April in the year ’83 that I woke one morning to find "
                "Sherlock Holmes standing, fully dressed, by the side of my bed. He was "
                "a late riser, as a rule, and as the clock on the mantelpiece showed me "
                "that it was only a quarter-past seven, I blinked up at him in some "
                "surprise, and perhaps just a little resentment, for I was myself "
                "regular in my habits. “Very sorry to knock you up, Watson,” said he, "
                "“but it’s the common lot this morning. Mrs. Hudson has been knocked "
                "up, she retorted upon me, and I on you.” “What is it, then—a fire?” "
                "“No; a client. It seems that a young lady has arrived in a "
                "considerable state of excitement, who insists upon seeing me. She is "
                "waiting now in the sitting-room. Now, when young ladies wander about "
                "the metropolis at this hour of the morning, and knock sleepy people up "
                "out of their beds, I presume that it is something very pressing which "
                "they have to communicate. Should it prove to be an interesting case, "
                "you would, I am sure, wish to follow it from the outset. I thought, at "
                "any rate, that I should call you and give you the chance.” “My dear "
                "fellow, I would not miss it for anything.” I had no keener pleasure "
                "than in following Holmes in his professional investigations, and in "
                "admiring the rapid deductions, as swift as intuitions, and yet always "
                "founded on a logical basis with which he unravelled the problems which "
                "were submitted to him. I rapidly threw on my clothes and was ready in "
                "a few minutes to accompany my friend down to the sitting-room.",
    },
    "the-necklace": {
        "title": "The Necklace",
        "author": "Guy de Maupassant",
        "source": "Original Short Stories, Vol. 4 (Project Gutenberg #3080)",
        "text": "The girl was one of those pretty and charming young creatures who "
                "sometimes are born, as if by a slip of fate, into a family of clerks. "
                "She had no dowry, no expectations, no way of being known, understood, "
                "loved, married by any rich and distinguished man; so she let herself be "
                "married to a little clerk of the Ministry of Public Instruction. She "
                "dressed plainly because she could not dress well, but she was unhappy "
                "as if she had really fallen from a higher station; since with women "
                "there is neither caste nor rank, for beauty, grace and charm take the "
                "place of family and birth. Natural ingenuity, instinct for what is "
                "elegant, a supple mind are their sole hierarchy, and often make of "
                "women of the people the equals of the very greatest ladies. Mathilde "
                "suffered ceaselessly, feeling herself born to enjoy all delicacies and "
                "all luxuries. She was distressed at the poverty of her dwelling, at the "
                "bareness of the walls, at the shabby chairs, the ugliness of the "
                "curtains. All those things, of which another woman of her rank would "
                "never even have been conscious, tortured her and made her angry. The "
                "sight of the little Breton peasant who did her humble housework aroused "
                "in her despairing regrets and bewildering dreams. She thought of silent "
                "antechambers hung with Oriental tapestry, illumined by tall bronze "
                "candelabra, and of two great footmen in knee breeches who sleep in the "
                "big armchairs, made drowsy by the oppressive heat of the stove. She "
                "thought of long reception halls hung with ancient silk, of the dainty "
                "cabinets containing priceless curiosities and of the little coquettish "
                "perfumed reception rooms made for chatting at five o'clock with "
                "intimate friends, with men famous and sought after, whom all women envy "
                "and whose attention they all desire. When she sat down to dinner, "
                "before the round table covered with a tablecloth in use three days, "
                "opposite her husband, who uncovered the soup tureen and declared with a "
                "delighted air, “Ah, the good soup! I don't know anything better than "
                "that,” she thought of dainty dinners, of shining silverware, of "
                "tapestry that peopled the walls with ancient personages and with "
                "strange birds flying in the midst of a fairy forest; and she thought of "
                "delicious dishes served on marvellous plates and of the whispered "
                "gallantries to which you listen with a sphinxlike smile while you are "
                "eating the pink meat of a trout or the wings of a quail. She had no "
                "gowns, no jewels, nothing. And she loved nothing but that. She felt "
                "made for that. She would have liked so much to please, to be envied, to "
                "be charming, to be sought after. She had a friend, a former schoolmate "
                "at the convent, who was rich, and whom she did not like to go to see "
                "any more because she felt so sad when she came home. But one evening "
                "her husband reached home with a triumphant air and holding a large "
                "envelope in his hand.",
    },
    "open-window": {
        "title": "The Open Window",
        "author": "Saki (H. H. Munro)",
        "source": "Beasts and Super-Beasts (Project Gutenberg #269)",
        "text": "“My aunt will be down presently, Mr. Nuttel,” said a very self-possessed "
                "young lady of fifteen; “in the meantime you must try and put up with "
                "me.” Framton Nuttel endeavoured to say the correct something which "
                "should duly flatter the niece of the moment without unduly discounting "
                "the aunt that was to come. Privately he doubted more than ever whether "
                "these formal visits on a succession of total strangers would do much "
                "towards helping the nerve cure which he was supposed to be undergoing. "
                "“I know how it will be,” his sister had said when he was preparing to "
                "migrate to this rural retreat; “you will bury yourself down there and "
                "not speak to a living soul, and your nerves will be worse than ever from "
                "moping. I shall just give you letters of introduction to all the people "
                "I know there. Some of them, as far as I can remember, were quite nice.” "
                "Framton wondered whether Mrs. Sappleton, the lady to whom he was "
                "presenting one of the letters of introduction, came into the nice "
                "division. “Do you know many of the people round here?” asked the niece, "
                "when she judged that they had had sufficient silent communion. “Hardly a "
                "soul,” said Framton. “My sister was staying here, at the rectory, you "
                "know, some four years ago, and she gave me letters of introduction to "
                "some of the people here.” He made the last statement in a tone of "
                "distinct regret. “Then you know practically nothing about my aunt?” "
                "pursued the self-possessed young lady. “Only her name and address,” "
                "admitted the caller. He was wondering whether Mrs. Sappleton was in the "
                "married or widowed state. An undefinable something about the room seemed "
                "to suggest masculine habitation. “Her great tragedy happened just three "
                "years ago,” said the child; “that would be since your sister’s time.” "
                "“Her tragedy?” asked Framton; somehow in this restful country spot "
                "tragedies seemed out of place. “You may wonder why we keep that window "
                "wide open on an October afternoon,” said the niece, indicating a large "
                "French window that opened on to a lawn. “It is quite warm for the time "
                "of the year,” said Framton; “but has that window got anything to do with "
                "the tragedy?” “Out through that window, three years ago to a day, her "
                "husband and her two young brothers went off for their day’s shooting. "
                "They never came back. In crossing the moor to their favourite "
                "snipe-shooting ground they were all three engulfed in a treacherous "
                "piece of bog. It had been that dreadful wet summer, you know, and places "
                "that were safe in other years gave way suddenly without warning. Their "
                "bodies were never recovered. That was the dreadful part of it.” Here the "
                "child’s voice lost its self-possessed note and became falteringly human. "
                "“Poor aunt always thinks that they will come back some day, they and the "
                "little brown spaniel that was lost with them, and walk in at that window "
                "just as they used to do.",
    },
}
